language: node_js
node_js:
  - "node"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: main
  - skip_cleanup: true
    provider: script
    script: npm run deploy-branch
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "main" && "$TRAVIS_BRANCH" != "gh-pages"'
